---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
      - name: Starting minikube
        shell: minikube start
      - name: Pull his service. 
        shell: | 
          eval $(minikube docker-env)
          docker pull prarthanaus0597/his-service:1.0
          docker tag prarthanaus0597/his-service:1.0 his-service:1.0
          docker rmi prarthanaus0597/his-service:1.0
      - name: Pull cms service. 
        shell: | 
          eval $(minikube docker-env)
          docker pull prarthanaus0597/cms-service:1.0
          docker tag prarthanaus0597/cms-service:1.0 cms-service:1.0
          docker rmi prarthanaus0597/cms-service:1.0

      - name: Pull admin service. 
        shell: | 
          eval $(minikube docker-env)
          docker pull prarthanaus0597/admin-service:1.0
          docker tag prarthanaus0597/admin-service:1.0 admin-service:1.0
          docker rmi prarthanaus0597/admin-service:1.0
          
      - name: Pull patient service. 
        shell: | 
          eval $(minikube docker-env)
          docker pull prarthanaus0597/patient-service:1.0
          docker tag prarthanaus0597/patient-service:1.0 patient-service:1.0
          docker rmi prarthanaus0597/patient-service:1.0
          
      - name: Pull his front end. 
        shell: | 
          eval $(minikube docker-env)
          docker pull prarthanaus0597/his-frontend-k8s:1.0
          docker tag prarthanaus0597/his-frontend-k8s:1.0 his-frontend-k8s:1.0
          docker rmi prarthanaus0597/his-frontend-k8s:1.0
            
      - name: Pull patient front end. 
        shell: | 
          eval $(minikube docker-env)
          docker pull prarthanaus0597/patient-frontend-k8s:1.0
          docker tag prarthanaus0597/patient-frontend-k8s:1.0 patient-frontend-k8s:1.0
          docker rmi prarthanaus0597/patient-frontend-k8s:1.0
          
      - name: Delete all the none named images. 
        shell: | 
          eval $(minikube docker-env)
          docker images | awk '$1 == "<none>" {print $3}' | xargs -I {} docker rmi {}

         
 



   

