---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: prarthanaus0597/cms-service:latest
        source: pull
    - name: Pull image
      docker_image:
        name: prarthanaus0597/admin-service:latest
        source: pull

    - name: Pull image
      docker_image:
        name: prarthanaus0597/his-service:latest
        source: pull

    - name: Pull image
      docker_image:
        name: prarthanaus0597/patient-service:latest
        source: pull

    - name: Pull image
      docker_image:
        name: prarthanaus0597/his-frontend-k8s:latest
        source: pull

    - name: Pull image
      docker_image:
        name: prarthanaus0597/patient-frontend-k8s:latest
        source: pull

    - name: Setup docker env
      shell: eval $(minikube docker-env)

    - name: Starting minikube
      shell: minikube start

